# Version de la syntaxe Docker Compose
version: '3.8'

# Définition des services (conteneurs)
services:
  # Le nom du service pour Redis
  redis-auth:
    # L'image Docker à utiliser
    image: "redis:7-alpine"
    # Nom du conteneur pour une identification facile
    container_name: soldstack-redis-auth
    # Mappage des ports : port_de_la_machine:port_du_conteneur
    ports:
      - "6379:6379"
    # Configuration pour que le service redémarre en cas de crash
    restart: unless-stopped
