name: CI - Discovery Service

on:
  push:
    paths:
      - "backend/discovery-service/**"
      - "backend/common/**"
  pull_request:
    paths:
      - "backend/discovery-service/**"
      - "backend/common/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"

      - name: Build Discovery Service
        run: ./gradlew :backend:discovery-service:build
